spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Test
    username: root
    password: 123456

    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update

server:
  port: 8182

mybatis:
  type-aliases-package: com.example.springboottest.entity
  mapper-locations: classpath:mapper/*.xml

